config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do

    resources :products, only: [:show]
    resources :categories, only: [:show]

    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  MAX_RELATED_PRODUCTS_SIZE = 8
  scope :related_products, -> (product) {
    where(
      id: Spree::Product.includes(:taxons)
        .references(:spree_products_taxons)
        .where("spree_products_taxons.taxon_id": product.taxons.ids)
        .distinct.ids
    )
    .where.not(id: product.id)
  }

  scope :sort_by_newest, -> {
    order(available_on: :desc)
  }

  scope :limit_for_related_products, -> {
    limit(MAX_RELATED_PRODUCTS_SIZE)
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  before_action :set_display, only: :show

  def show
    @taxon = Spree::Taxon.find(params[:id])
    @products = Spree::Product.in_taxon(@taxon)
    @taxonomies = Spree::Taxonomy.all.includes(:root)
  end

  private
  # 表示形式の設定
  def set_display
    @display ||=
      if params[:display] == 'list'
        'list'
      else
        'grid'
      end
  end

end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController

  def show
    @product = Spree::Product.friendly.find(params[:id])
    @related_products = Spree::Product.related_products(@product)
      .sort_by_newest
      .limit_for_related_products
    @taxons = get_taxons(@product)
  end

  private
  def get_taxons(product)
    if params[:taxon_id]
      Spree::Taxon.find(params[:taxon_id]).self_and_ancestors
    elsif product.taxons.present?
      product.taxons.first.self_and_ancestors
    end
  end

end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページのタイトルを返す
  def full_title(title = '')
    base_title = 'Potepanec'
    title.blank? ? base_title : "#{base_title} - #{title}"
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def categories_params
    {display: params[:display]}
  end

end

app/views/potepan/categories/_products_grid.html.erb
<div class="row">
  <% products.each do |product| %>
    <div class="col-sm-4 col-xs-12">
      <div class="productBox">
        <div class="productImage clearfix">
          <%= image_tag(product.display_image.attachment.url(:small), :alt => "#{product.name} image") %>
          <div class="productMasking">
            <ul class="list-inline btn-group" role="group">
              <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
              <li>
                <%= link_to potepan_cart_page_path, class: "btn btn-default" do %>
                  <i class="fa fa-shopping-cart"></i>
                <% end %>
              </li>
              <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
            </ul>
          </div>
        </div>
        <div class="productCaption clearfix">
          <%= link_to potepan_product_path(product.friendly_id, taxon_id: taxon.id) do %>
            <h5><%= product.name %></h5>
          <% end %>
          <h3><%= product.display_price %></h3>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/_products_list.html.erb
<div class="row productListSingle">
  <% products.each do |product| %>
    <div class="col-xs-12 productCard">
      <div class="media">
        <div class="media-left">
          <%= image_tag(product.display_image.attachment.url(:product), :alt => "#{product.name} image") %>
          <span class="maskingImage"><a data-toggle="modal" href=".quick-view" class="btn viewBtn">Quick View</a></span>
        </div>
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to product.name, potepan_product_path(product.friendly_id, taxon_id: taxon.id) %>
          </h4>
          <p><%= product.description %></p>
          <h3><%= product.display_price %></h3>
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart" aria-hidden="true"></i></button>
            <button type="button" class="btn btn-default" onclick="location.href='cart-page.html';"><i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/_taxonomy.html.erb
<div class="panel panel-default <%= taxonomy.name.camelize %>">
  <div class="panel-heading"><%= taxonomy.name %></div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% taxonomy.root.children.each do |taxon| %>
          <li>
            <% if taxon.children.empty? %>
              <%# taxonに子taxonがない場合はアコーディオンを作らない %>
              <%= link_to potepan_category_path(taxon.id, categories_params) do %>
                <%= taxon.name %> <span>(<%= taxon.products.size %>)</span>
              <% end %>
            <% else %>
              <a href="javascript:;" data-toggle="collapse" data-target="#taxon-<%= taxon.id %>">
                <%= taxon.name %><i class="fa fa-plus"></i>
              </a>
              <ul id="taxon-<%= taxon.id %>" class="collapse collapseItem">
                <%# root taxonの子taxonをリストにする %>
                <% taxon.children.each do |child_taxon| %>
                  <li>
                    <%= link_to potepan_category_path(child_taxon.id, categories_params) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i><%= child_taxon.name %> <span>(<%= child_taxon.products.size %>)</span>
                    <% end %>
                    <%# 孫taxon以下は出力しない %>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<% content_for(:page_title, @taxon.name) %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:page_title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <% @taxon.ancestors.each do |ancestor| %>
            <li>
              <%= link_to ancestor.name, potepan_category_path(ancestor.id) %>
            </li>
          <% end %>
          <li class="active"><%= @taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <%= render 'sidebar', taxonomies: @taxonomies %>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <%= render 'filter_area', display: @display%>
        <% if @display == 'grid' %>
          <%= render 'products_grid', products: @products, taxon: @taxon %>
        <% elsif @display == 'list' %>
          <%= render 'products_list', products: @products, taxon: @taxon %>
        <% end %>
      </div>
    </div>
  </div>
</section>

<%= render 'shared/partners_logo_slider' %>
<%= render 'potepan/products/product_quick_view_modal' %>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent relatedProducts">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% if related_products.present? %>
    <% related_products.each do |product| %>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <% if product.images.present? %>
              <%= image_tag(product.master_images.first.attachment.url(:small), :alt => "#{product.name}-img") %>
            <% else %>
              <%= image_tag("img/products/signle-product/product-slide-small-01.jpg") %>
            <% end %>
            <div class="productMasking">
              <ul class="list-inline btn-group" role="group">
                <li>
                  <a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a>
                </li>
                <li>
                  <%= link_to potepan_cart_page_path, class: "btn btn-default" do %>
                    <i class="fa fa-shopping-cart"></i>
                  <% end %>
                </li>
                <li>
                  <a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a>
                </li>
              </ul>
            </div>
          </div>
          <div class="productCaption clearfix">
            <%= link_to potepan_product_path(product.friendly_id) do %>
              <h5><%= product.name %></h5>
              <h3><%= product.display_price %></h3>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <p>関連商品は見つかりませんでした</p>
    </div>
  <% end %>
</div>

app/views/potepan/products/show.html.erb
<% content_for(:page_title, @product.name) %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <% if @taxons.present? %>
            <% @taxons.each do |taxon| %>
              <li>
                <%= link_to taxon.name, potepan_category_path(taxon.id) %>
              </li>
            <% end %>
          <% end %>
          <li class="active"><%= @product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <%= render 'carousel', product: @product %>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <% if @taxons.present? %>
                <li>
                  <%= link_to potepan_category_path(@taxons.last.id) do %>
                    <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                  <% end %>
                </li>
              <% end %>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <%= render 'cart_form', product: @product, place: "single" %>
            <%= render 'tab_area' %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'related_products', related_products: @related_products %>
  </div>
</section>

<%= render 'product_quick_view_modal', product: @product %>

app/views/potepan/sample/blog_single_left_sidebar.html.erb
<% content_for(:page_title, "Blog Right Sidebar") %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:page_title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <li class="active"><%= yield(:page_title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix blogPage singleBlog">
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-sm-8 col-md-push-3 col-sm-push-4 col-xs-12">
        <div class="row">
          <div class="col-xs-12">
            <div class="thumbnail">
              <%= image_tag("img/blog/blog-01.jpg", :alt => "blog-image") %>
              <div class="caption">
                <div class="row">
                  <div class="col-md-12 col-sm-12 col-xs-12">
                    <h3>記事タイトル </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>

                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>

                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p>
                  </div>
                </div>
              </div>
              <ul class="pager">
                <li class="previous"><a href="#">前の記事へ</a></li>
                <li class="next"><a href="#">次の記事へ</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-4 col-md-pull-9 col-sm-pull-8 col-xs-12 sideBar">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search" aria-describedby="basic-addon2">
          <a href="#" class="input-group-addon" id="basic-addon2"><i class="fa fa-search"></i></a>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">カテゴリー</div>
          <div class="panel-body">
            <ul class="list-unstyle sidebar-list">
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>アクセサリー <span>(6)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>バッグ <span>(6)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>洋服 <span>(25)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>ベッド &amp; バス <span>(2)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>スイミング <span>(5)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>スポーツウェア &amp; シューズ <span>(3)</span></a></li>
            </ul>
          </div>
        </div>
        <div class="panel panel-default recentBlogPosts">
          <div class="panel-heading">最新記事</div>
          <div class="panel-body">
            <div class="media">
              <a class="media-left" href="blog_single_right_sidebar.html">
                <%= image_tag("img/blog/blog-small-01.jpg", :class => "media-object", :alt => "Image") %>
              </a>
              <div class="media-body">
                <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
              </div>
            </div>
            <div class="media">
              <a class="media-left" href="blog_single_right_sidebar.html">
                <%= image_tag("img/blog/blog-small-02.jpg", :class => "media-object", :alt => "Image") %>
              </a>
              <div class="media-body">
                <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
              </div>
            </div>
            <div class="media">
              <a class="media-left" href="blog_single_right_sidebar.html">
                <%= image_tag("img/blog/blog-small-03.jpg", :class => "media-object", :alt => "Image") %>
              </a>
              <div class="media-body">
                <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/sample/cart_page.html.erb
<% content_for(:page_title, "Cart Page") %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:page_title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <li class="active"><%= yield(:page_title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix cartListWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="cartListInner">
          <form action="#">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th></th>
                    <th>商品名</th>
                    <th>価格</th>
                    <th>数</th>
                    <th>小計</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="updateArea">
             <!--  <div class="input-group">
                <input type="text" class="form-control" placeholder="I have a discount coupon" aria-describedby="basic-addon2">
                <a href="#" class="btn input-group-addon" id="basic-addon2">apply coupon</a>
              </div> -->
              <a href="#" class="btn">アップデート</a>
            </div>
            <div class="totalAmountArea">
              <div class="col-sm-4 col-sm-offset-8 col-xs-12">
                <ul class="list-unstyled">
                  <li>小計 <span>792円</span></li>
                  <li>消費税 <span>18円</span></li>
                  <li>総計 <span class="grandTotal">810円</span></li>
                </ul>
              </div>
            </div>
            <div class="checkBtnArea">
              <a href="checkout_step_1.html" class="btn btn-primary btn-block">購入する<i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/sample/checkout_complete.html.erb
<% content_for(:page_title, "Order Completed") %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:page_title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <li class="active"><%= yield(:page_title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix setp5">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="thanksContent">
          <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
          <h3>Shipping Details</h3>
          <div class="thanksInner">
            <div class="row">
              <div class="col-sm-6 col-xs-12 tableBlcok">
                <address>
                  <span>Shipping address:</span> <a href="mailto:adamsmith@bigbag.com">adamsmith@bigbag.com</a> <br>
                  <span>Email:</span> <a href="mailto:adamsmith@bigbag.com">adamsmith@bigbag.com</a> <br>
                  <span>Phone:</span> +884 5452 6432
                </address>
              </div>
              <div class="col-sm-6 col-xs-12">
                <div class="well">
                  <h2><small>Order ID</small>9547</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/sample/privacy_policy.html.erb
<% content_for(:page_title, "Privacy Policy") %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:page_title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <li class="active"><%= yield(:page_title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix genricContent">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h3>プライバシーポリシー</h3>
        <p>株式会社 xxx（以下「当社」）は、以下のとおり個人情報保護方針を定め、個人情報保護の仕組みを構築し、全従業員に個人情報保護の重要性の認識と取組みを徹底させることにより、個人情報の保護を推進致します。</p>

        <h5>個人情報の管理</h5>
        <p>当社は、お客さまの個人情報を正確かつ最新の状態に保ち、個人情報への不正アクセス・紛失・破損・改ざん・漏洩などを防止するため、セキュリティシステムの維持・管理体制の整備・社員教育の徹底等の必要な措置を講じ、安全対策を実施し個人情報の厳重な管理を行ないます。</p>

        <h5>個人情報の利用目的</h5>
        <p>お客さまからお預かりした個人情報は、当社からのご連絡や業務のご案内やご質問に対する回答として、電子メールや資料のご送付に利用いたします。</p>

        <h5>個人情報の第三者への開示・提供の禁止</h5>
        <p>当社は、お客さまよりお預かりした個人情報を適切に管理し、次のいずれかに該当する場合を除き、個人情報を第三者に開示いたしません。<br><br>
        ・お客さまの同意がある場合<br>
        ・お客さまが希望されるサービスを行なうために当社が業務を委託する業者に対して開示する場合<br>
        ・法令に基づき開示することが必要である場合</p>
        <h5>個人情報の安全対策</h5>
        <p>当社は、個人情報の正確性及び安全性確保のために、セキュリティに万全の対策を講じています。</p>
        <h5>ご本人の照会</h5>
        <p>お客さまがご本人の個人情報の照会・修正・削除などをご希望される場合には、ご本人であることを確認の上、対応させていただきます。</p>
        <h5>法令、規範の遵守と見直し</h5>
        <p>当社は、保有する個人情報に関して適用される日本の法令、その他規範を遵守するとともに、本ポリシーの内容を適宜見直し、その改善に努めます。</p>

        <h5>お問い合せ</h5>
        <p>当社の個人情報の取扱に関するお問い合せは下記までご連絡ください。<br>
        株式会社 xxx <br>
        〒xxx-xxxx　xx県xx市xx町x-x-x <br>
        TEL:XXX-XXX-XXXX FAX:XXX-XXX-XXXX <br>
        Mail:info@example.co.jp <br>
        </p>
      </div>
    </div>
  </div>
</section>